### ISSUE TITLE
Stybliski-Tang function breaks the optimizer

### ISSUE THREAD

**Issue by clutchkingasiimov** [clutchkingasiimov/nio#7]

**Comment by clutchkingasiimov** [comment]
The function does not return a valid output from the optimizer

```python 
#Error output from Streamlit
Traceback (most recent call last):
  File "/home/sauraj_hackerman/miniconda3/envs/nio/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/sauraj_hackerman/nio/webapp.py", line 111, in <module>
    opt = requests.get('http://127.0.0.1:8000/model/optimize').json()
  File "/home/sauraj_hackerman/miniconda3/envs/nio/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

and 

```python 
#Error output from FastAPI
 File "/home/sauraj_hackerman/miniconda3/envs/nio/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/sauraj_hackerman/nio/main.py", line 53, in run_optimizer
    x, y, f, n = cs.optimize(return_nests=True)
  File "/home/sauraj_hackerman/nio/model/cso.py", line 159, in optimize
    nests = generate_nests(self.soln_space, self.nests,
  File "/home/sauraj_hackerman/nio/model/funcs.py", line 73, in generate_nests
    new_solnspace = column_stack((nests, func_output))
  File "<__array_function__ internals>", line 200, in column_stack
  File "/home/sauraj_hackerman/miniconda3/envs/nio/lib/python3.9/site-packages/numpy/lib/shape_base.py", line 656, in column_stack
    return _nx.concatenate(arrays, 1)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 15 and the array at index 1 has size 1

```
